"""
Apply Isolated Classifier Outputs to team_evidence_v2.json

Purpose
-------
The isolated classifier should NOT rewrite the full evidence file.
It should only output classifier results like:

{
  "classifier_outputs": [
    {
      "event_id": "E001",
      "classifier_output": {
        "intent_category": "benign",
        "contains_request_for_credentials": false,
        "contains_instruction_to_model": false
      }
    }
  ]
}

This script reads:
1. an evidence JSON file, usually team_evidence_v2_classifier_output_empty.json
2. a classifier outputs JSON file generated by the isolated classifier

Then it writes a new evidence JSON file where ONLY classifier_output is updated.
All other evidence fields remain unchanged.

Typical usage
-------------
python src/apply_classifier_outputs.py ^
  --evidence data/processed/team_evidence_v2_classifier_output_empty.json ^
  --classifier-outputs data/processed/classifier_outputs.json ^
  --output data/processed/team_evidence_v2.json

Optional strict mode:
python src/apply_classifier_outputs.py ^
  --evidence data/processed/team_evidence_v2_classifier_output_empty.json ^
  --classifier-outputs data/processed/classifier_outputs.json ^
  --output data/processed/team_evidence_v2.json ^
  --strict
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List, Set, Tuple


REQUIRED_CLASSIFIER_KEYS = {
    "intent_category",
    "contains_request_for_credentials",
    "contains_instruction_to_model",
}

ALLOWED_CLASSIFIER_KEYS = REQUIRED_CLASSIFIER_KEYS

ALLOWED_INTENT_CATEGORIES = {
    "benign",
    "credential_request",
    "phishing_like",
    "prompt_injection_like",
    "malware_delivery",
    "unknown",
}


def load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def write_json(data: Any, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def normalize_classifier_outputs(data: Any) -> List[Dict[str, Any]]:
    """
    Accept both:
    1. {"classifier_outputs": [...]}
    2. [...]

    Return classifier_outputs list.
    """
    if isinstance(data, dict):
        outputs = data.get("classifier_outputs")
    else:
        outputs = data

    if not isinstance(outputs, list):
        raise ValueError("classifier outputs must be a JSON object with key 'classifier_outputs' or a JSON array")

    return outputs


def validate_classifier_output_shape(classifier_output: Any) -> Tuple[bool, List[str]]:
    """
    Basic shape validation before applying output.

    Full validation is still handled by classifier_output_validator.py.
    This function prevents obviously malformed objects from being written back.
    """
    errors: List[str] = []

    if not isinstance(classifier_output, dict):
        return False, ["classifier_output_not_object"]

    keys = set(classifier_output.keys())
    missing = REQUIRED_CLASSIFIER_KEYS - keys
    extra = keys - ALLOWED_CLASSIFIER_KEYS

    if missing:
        errors.append("missing_required_keys:" + "|".join(sorted(missing)))
    if extra:
        errors.append("unexpected_extra_keys:" + "|".join(sorted(extra)))

    intent = classifier_output.get("intent_category")
    if intent not in ALLOWED_INTENT_CATEGORIES:
        errors.append("invalid_intent_category")

    if not isinstance(classifier_output.get("contains_request_for_credentials"), bool):
        errors.append("contains_request_for_credentials_not_boolean")

    if not isinstance(classifier_output.get("contains_instruction_to_model"), bool):
        errors.append("contains_instruction_to_model_not_boolean")

    return len(errors) == 0, errors


def build_output_map(outputs: List[Dict[str, Any]]) -> Tuple[Dict[str, Dict[str, Any]], List[str]]:
    """
    Build event_id -> classifier_output map.

    Duplicate event_id is treated as an error because it can overwrite results.
    """
    output_map: Dict[str, Dict[str, Any]] = {}
    errors: List[str] = []

    for idx, item in enumerate(outputs, start=1):
        if not isinstance(item, dict):
            errors.append(f"row_{idx}:output_item_not_object")
            continue

        event_id = item.get("event_id")
        classifier_output = item.get("classifier_output")

        if not isinstance(event_id, str) or not event_id.strip():
            errors.append(f"row_{idx}:missing_or_invalid_event_id")
            continue

        event_id = event_id.strip()

        if event_id in output_map:
            errors.append(f"{event_id}:duplicate_event_id_in_classifier_outputs")
            continue

        valid, shape_errors = validate_classifier_output_shape(classifier_output)
        if not valid:
            errors.extend([f"{event_id}:{err}" for err in shape_errors])
            continue

        output_map[event_id] = classifier_output

    return output_map, errors


def apply_outputs(
    evidence_records: List[Dict[str, Any]],
    output_map: Dict[str, Dict[str, Any]],
    strict: bool = False,
) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
    """
    Apply classifier_output by event_id.

    strict=False:
      - update matched records
      - leave unmatched evidence records unchanged
      - report missing / extra event ids

    strict=True:
      - fail if any evidence event_id is missing from classifier outputs
      - fail if classifier outputs contain event_id not in evidence
    """
    if not isinstance(evidence_records, list):
        raise ValueError("evidence file must be a JSON array")

    evidence_ids: Set[str] = set()
    duplicate_evidence_ids: Set[str] = set()

    for idx, record in enumerate(evidence_records, start=1):
        if not isinstance(record, dict):
            raise ValueError(f"evidence row {idx} is not an object")

        event_id = record.get("event_id")
        if not isinstance(event_id, str) or not event_id.strip():
            raise ValueError(f"evidence row {idx} has missing or invalid event_id")

        event_id = event_id.strip()
        if event_id in evidence_ids:
            duplicate_evidence_ids.add(event_id)
        evidence_ids.add(event_id)

    if duplicate_evidence_ids:
        raise ValueError("duplicate event_id in evidence file: " + ", ".join(sorted(duplicate_evidence_ids)))

    output_ids = set(output_map.keys())

    missing_in_outputs = sorted(evidence_ids - output_ids)
    extra_in_outputs = sorted(output_ids - evidence_ids)

    if strict and missing_in_outputs:
        raise ValueError("classifier outputs missing event_id(s): " + ", ".join(missing_in_outputs))

    if strict and extra_in_outputs:
        raise ValueError("classifier outputs contain unknown event_id(s): " + ", ".join(extra_in_outputs))

    updated_records: List[Dict[str, Any]] = []
    updated_count = 0

    for record in evidence_records:
        event_id = record["event_id"]
        new_record = dict(record)

        if event_id in output_map:
            new_record["classifier_output"] = output_map[event_id]
            updated_count += 1

        updated_records.append(new_record)

    summary = {
        "evidence_count": len(evidence_records),
        "classifier_output_count": len(output_map),
        "updated_count": updated_count,
        "missing_in_classifier_outputs_count": len(missing_in_outputs),
        "extra_classifier_outputs_count": len(extra_in_outputs),
        "missing_in_classifier_outputs": missing_in_outputs,
        "extra_classifier_outputs": extra_in_outputs,
    }

    return updated_records, summary


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Apply isolated classifier outputs to evidence JSON by event_id."
    )
    parser.add_argument(
        "--evidence",
        type=Path,
        required=True,
        help="Input evidence JSON, usually team_evidence_v2_classifier_output_empty.json.",
    )
    parser.add_argument(
        "--classifier-outputs",
        type=Path,
        required=True,
        help="JSON file containing {'classifier_outputs': [...]} from isolated classifier.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="Output evidence JSON path.",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Fail if classifier outputs do not exactly match evidence event_ids.",
    )
    parser.add_argument(
        "--summary",
        type=Path,
        default=None,
        help="Optional path to write an apply summary JSON.",
    )

    args = parser.parse_args()

    evidence_data = load_json(args.evidence)
    classifier_outputs_data = load_json(args.classifier_outputs)

    classifier_outputs = normalize_classifier_outputs(classifier_outputs_data)
    output_map, output_errors = build_output_map(classifier_outputs)

    if output_errors:
        raise ValueError("invalid classifier outputs:\n" + "\n".join(output_errors))

    updated_records, summary = apply_outputs(
        evidence_records=evidence_data,
        output_map=output_map,
        strict=args.strict,
    )

    write_json(updated_records, args.output)

    if args.summary:
        write_json(summary, args.summary)

    print(f"wrote {args.output}")
    print(f"evidence_count={summary['evidence_count']}")
    print(f"classifier_output_count={summary['classifier_output_count']}")
    print(f"updated_count={summary['updated_count']}")
    print(f"missing_in_classifier_outputs_count={summary['missing_in_classifier_outputs_count']}")
    print(f"extra_classifier_outputs_count={summary['extra_classifier_outputs_count']}")

    if summary["missing_in_classifier_outputs_count"] > 0:
        print("warning: some evidence records were not updated because classifier outputs were missing")

    if summary["extra_classifier_outputs_count"] > 0:
        print("warning: some classifier outputs were ignored because event_id was not found in evidence")


if __name__ == "__main__":
    main()
