"""
Select Accepted Evidence for Main LLM

Purpose
-------
Filter team_evidence_v2.json using classifier_validation_report.csv.
Only evidence records whose classifier output is accepted will be forwarded
to the main LLM.

This script prevents rejected or suspicious isolated-classifier results from
influencing the main LLM reasoning stage.

Typical usage
-------------
python src/select_main_llm_evidence.py ^
  --evidence data/processed/team_evidence_v2.json ^
  --classifier-report data/processed/classifier_validation_report.csv ^
  --output data/processed/team_evidence_v2_main_llm_input.json ^
  --rejected-output data/processed/team_evidence_v2_rejected_by_classifier.json

Strict mode:
python src/select_main_llm_evidence.py ^
  --evidence data/processed/team_evidence_v2.json ^
  --classifier-report data/processed/classifier_validation_report.csv ^
  --output data/processed/team_evidence_v2_main_llm_input.json ^
  --strict
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any, Dict, List, Set, Tuple


ACCEPT_ACTIONS = {
    "accept",
    "accept_classifier_output",
}

ACCEPT_TRUE_VALUES = {
    "true",
    "1",
    "yes",
    "y",
}


def load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def write_json(data: Any, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def read_classifier_report(path: Path) -> Tuple[Set[str], Set[str], List[Dict[str, str]]]:
    """
    Return:
    - accepted event_ids
    - rejected event_ids
    - all rows

    This function supports reports generated by classifier_output_validator.py.
    It accepts records when:
    1. classifier_output_valid is true, OR
    2. action is accept / accept_classifier_output

    CLS adversarial test rows are ignored later because they do not exist in evidence.
    """
    accepted: Set[str] = set()
    rejected: Set[str] = set()
    rows: List[Dict[str, str]] = []

    with path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)
            event_id = (row.get("event_id") or "").strip()
            if not event_id:
                continue

            valid_text = (row.get("classifier_output_valid") or row.get("is_valid") or "").strip().lower()
            rejected_text = (row.get("classifier_output_rejected") or "").strip().lower()
            action = (row.get("action") or "").strip()

            is_accepted = valid_text in ACCEPT_TRUE_VALUES or action in ACCEPT_ACTIONS
            is_rejected = rejected_text in ACCEPT_TRUE_VALUES or action.startswith("reject")

            if is_accepted and not is_rejected:
                accepted.add(event_id)
            else:
                rejected.add(event_id)

    return accepted, rejected, rows


def split_evidence(
    evidence_records: List[Dict[str, Any]],
    accepted_ids: Set[str],
    rejected_ids: Set[str],
    strict: bool = False,
) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]], Dict[str, Any]]:
    if not isinstance(evidence_records, list):
        raise ValueError("evidence file must be a JSON array")

    accepted_records: List[Dict[str, Any]] = []
    rejected_records: List[Dict[str, Any]] = []
    missing_from_report: List[str] = []

    evidence_ids: Set[str] = set()

    for idx, record in enumerate(evidence_records, start=1):
        if not isinstance(record, dict):
            raise ValueError(f"evidence row {idx} is not an object")

        event_id = str(record.get("event_id", "")).strip()
        if not event_id:
            raise ValueError(f"evidence row {idx} has missing event_id")

        evidence_ids.add(event_id)

        if event_id in accepted_ids:
            accepted_records.append(record)
        elif event_id in rejected_ids:
            rejected_records.append(record)
        else:
            missing_from_report.append(event_id)
            rejected_records.append(record)

    report_ids = accepted_ids | rejected_ids
    extra_report_ids = sorted(report_ids - evidence_ids)
    missing_from_report = sorted(missing_from_report)

    if strict and missing_from_report:
        raise ValueError(
            "classifier report is missing evidence event_id(s): "
            + ", ".join(missing_from_report)
        )

    summary = {
        "evidence_count": len(evidence_records),
        "accepted_for_main_llm_count": len(accepted_records),
        "rejected_or_blocked_count": len(rejected_records),
        "missing_from_classifier_report_count": len(missing_from_report),
        "extra_report_ids_count": len(extra_report_ids),
        "missing_from_classifier_report": missing_from_report,
        "extra_report_ids": extra_report_ids,
    }

    return accepted_records, rejected_records, summary


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Filter evidence records so only accepted classifier outputs are forwarded to the main LLM."
    )
    parser.add_argument(
        "--evidence",
        type=Path,
        required=True,
        help="Path to data/processed/team_evidence_v2.json.",
    )
    parser.add_argument(
        "--classifier-report",
        type=Path,
        required=True,
        help="Path to data/processed/classifier_validation_report.csv.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("data/processed/team_evidence_v2_main_llm_input.json"),
        help="Output JSON for evidence accepted for main LLM.",
    )
    parser.add_argument(
        "--rejected-output",
        type=Path,
        default=None,
        help="Optional output JSON for rejected or blocked evidence.",
    )
    parser.add_argument(
        "--summary",
        type=Path,
        default=None,
        help="Optional output JSON summary.",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Fail if any evidence event_id is missing from classifier report.",
    )

    args = parser.parse_args()

    evidence_records = load_json(args.evidence)
    accepted_ids, rejected_ids, _ = read_classifier_report(args.classifier_report)

    accepted_records, rejected_records, summary = split_evidence(
        evidence_records=evidence_records,
        accepted_ids=accepted_ids,
        rejected_ids=rejected_ids,
        strict=args.strict,
    )

    write_json(accepted_records, args.output)

    if args.rejected_output:
        write_json(rejected_records, args.rejected_output)

    if args.summary:
        write_json(summary, args.summary)

    print(f"wrote {args.output}")
    print(f"evidence_count={summary['evidence_count']}")
    print(f"accepted_for_main_llm_count={summary['accepted_for_main_llm_count']}")
    print(f"rejected_or_blocked_count={summary['rejected_or_blocked_count']}")
    print(f"missing_from_classifier_report_count={summary['missing_from_classifier_report_count']}")
    print(f"extra_report_ids_count={summary['extra_report_ids_count']}")

    if args.rejected_output:
        print(f"wrote {args.rejected_output}")

    if args.summary:
        print(f"wrote {args.summary}")


if __name__ == "__main__":
    main()
